@baseURL = https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1
@id = <COPY_ID_HERE>

# Fetch all anime characters
GET {{baseURL}}/animeCharacters

###

# Fetch a single anime character by ID
GET {{baseURL}}/animeCharacters/{{id}}

###

# Create a new anime character
POST {{baseURL}}/animeCharacters
Content-Type: application/json

{
    "name": "Goku",
    "anime": "Dragon Ball Z",
    "powerLevel": 9001
}

###

# Delete an anime character
DELETE {{baseURL}}/animeCharacters/{{id}}

###

# Update an anime character
PATCH {{baseURL}}/animeCharacters/{{id}}
Content-Type: application/json

{
    "name": "Vegeta",
    "anime": "Dragon Ball Z",
    "powerLevel": 9500
}