@baseURL = https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1
@id = <COPY_ID_HERE>

GET https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1/students

###

GET https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1/students/{id}

###

POST https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1/students
Content-Type: application/json

{
    "name": "Brandon Brown",
    "class": "DWA"
}

###

DELETE https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1/students/{id}

###

PATCH https://bradleycruddemo-1b86f27b4c16.herokuapp.com/api/v1/students/{id}
Content-Type: application/json

{
    "name": "New Name",
    "class": "New Class"
}